export type Subject =
  | "Algebra 1"
  | "Algebra 2"
  | "Geometry"
  | "Precalculus"
  | "Calculus"
  | "SAT/ACT Math"
  | "ELA";

export const ALL_SUBJECTS: Subject[] = [
  "Algebra 1",
  "Algebra 2",
  "Geometry",
  "Precalculus",
  "Calculus",
  "SAT/ACT Math",
  "ELA",
];

export type Skill = {
  id: string;
  name: string;
  subject: Subject[];
  domain: "Math" | "ELA";
  difficulty: "foundational" | "intermediate" | "advanced";
  tags: string[];
  calculatorAllowed?: boolean; // relevant for SAT/ACT Math only
  /** Georgia K-12 Mathematics / ELA Standards course code, e.g. "A.FGR.2" or "9-12.T.T.1" */
  standardCode?: string;
  /** The "Big Idea" / reasoning strand the standard belongs to, e.g. "Functional & Graphical Reasoning" */
  standardName?: string;
};

// Source: Georgia Department of Education, "Georgia's K-12 Mathematics Standards
// Curriculum Map" series (approved May 2023, implementation Fall 2023) for Algebra,
// Geometry, Advanced Algebra, and Precalculus & AP Precalculus; "2021 Calculus
// Standards" (August 2021) for Calculus; and "Georgia's K-12 English Language Arts
// (ELA) Standards: Language, Texts, & Practices, 9th Grade-12th Grade" (approved
// May 2023) for ELA. The app's course names (Algebra 1, Algebra 2, etc.) map onto
// GA's official course names: Algebra 1 -> Algebra: Concepts & Connections,
// Algebra 2 -> Advanced Algebra: Concepts & Connections, Geometry -> Geometry:
// Concepts & Connections.
export const SKILLS: Skill[] = [
  // ── Algebra 1 (Algebra: Concepts & Connections) ─────────────────────────────
  {
    id: "alg1-linear-functions",
    name: "Modeling Linear Functions",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["arithmetic sequences", "linear graphs", "domain and range", "function notation"],
    calculatorAllowed: true,
    standardCode: "A.FGR.2",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "alg1-linear-inequalities",
    name: "Analyzing Linear Inequalities",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["two-variable inequalities", "systems of inequalities", "graphing constraints"],
    calculatorAllowed: true,
    standardCode: "A.PAR.4",
    standardName: "Patterning & Algebraic Reasoning",
  },
  {
    id: "alg1-rational-irrational",
    name: "Rational and Irrational Numbers",
    subject: ["Algebra 1"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["radicals", "square roots", "cube roots", "number system"],
    standardCode: "A.NR.5",
    standardName: "Numerical Reasoning",
  },
  {
    id: "alg1-quadratic-equations",
    name: "Modeling Quadratic Equations",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["factoring", "quadratic formula", "completing the square", "real-life modeling"],
    calculatorAllowed: true,
    standardCode: "A.PAR.6",
    standardName: "Patterning & Algebraic Reasoning",
  },
  {
    id: "alg1-quadratic-functions",
    name: "Quadratic Functions and Graphs",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["parabolas", "vertex form", "transformations", "key features"],
    calculatorAllowed: true,
    standardCode: "A.FGR.7",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "alg1-exponential-expressions",
    name: "Exponential Expressions and Equations",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["one-variable exponential equations", "growth and decay", "parameters"],
    calculatorAllowed: true,
    standardCode: "A.PAR.8",
    standardName: "Patterning & Algebraic Reasoning",
  },
  {
    id: "alg1-exponential-functions",
    name: "Analyzing Exponential Functions",
    subject: ["Algebra 1"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["exponential graphs", "geometric sequences", "comparing function families"],
    standardCode: "A.FGR.9",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "alg1-data-analysis",
    name: "Investigating Data",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["univariate data", "bivariate data", "scatter plots", "line of best fit", "correlation"],
    calculatorAllowed: true,
    standardCode: "A.DSR.10",
    standardName: "Data & Statistical Reasoning",
  },
  {
    id: "alg1-geometric-connections",
    name: "Algebraic Connections to Geometric Concepts",
    subject: ["Algebra 1", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["distance formula", "midpoint formula", "slope", "area", "perimeter"],
    calculatorAllowed: true,
    standardCode: "A.GSR.3",
    standardName: "Geometric & Spatial Reasoning",
  },

  // ── Geometry (Geometry: Concepts & Connections) ─────────────────────────────
  {
    id: "geo-polynomial-expressions",
    name: "Polynomial Expressions",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["adding", "subtracting", "multiplying polynomials", "geometric justification"],
    standardCode: "G.PAR.2",
    standardName: "Patterning & Algebraic Reasoning",
  },
  {
    id: "geo-foundations-construction-proof",
    name: "Geometric Foundations, Construction, and Proof",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["points, lines, planes", "compass and straightedge", "angle relationships", "proofs"],
    standardCode: "G.GSR.4",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "geo-congruence",
    name: "Congruence",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["transformations", "rotations", "reflections", "translations", "triangle congruence"],
    standardCode: "G.GSR.3",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "geo-similarity",
    name: "Similarity",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["dilations", "scale factor", "similar triangles", "proportional reasoning"],
    standardCode: "G.GSR.5",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "geo-right-triangle-trig",
    name: "Right Triangle Trigonometry",
    subject: ["Geometry", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["sine", "cosine", "tangent", "Pythagorean theorem", "complementary angles"],
    calculatorAllowed: true,
    standardCode: "G.GSR.6",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "geo-circles",
    name: "Circles",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["chords", "tangents", "secants", "arc length", "sector area", "radians", "unit circle"],
    standardCode: "G.GSR.8",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "geo-equations-measurement",
    name: "Equations and Measurement",
    subject: ["Geometry", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["volume formulas", "prisms", "cylinders", "pyramids", "cones", "spheres"],
    calculatorAllowed: true,
    standardCode: "G.GSR.9",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "geo-probability",
    name: "Probability of Compound Events",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["addition rule", "multiplication rule", "permutations", "combinations", "expected value"],
    standardCode: "G.PR.10",
    standardName: "Probabilistic Reasoning",
  },
  {
    id: "geo-two-way-frequency",
    name: "Two-Way Frequency Tables",
    subject: ["Geometry"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["categorical data", "conditional probability", "contingency tables"],
    standardCode: "G.DSR.11",
    standardName: "Data & Statistical Reasoning",
  },

  // ── Algebra 2 (Advanced Algebra: Concepts & Connections) ────────────────────
  {
    id: "alg2-statistics",
    name: "Descriptive and Inferential Statistics",
    subject: ["Algebra 2"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["sampling", "z-scores", "empirical rule", "confidence intervals"],
    standardCode: "AA.DSR.2",
    standardName: "Data & Statistical Reasoning",
  },
  {
    id: "alg2-exponential-log",
    name: "Exponential and Logarithmic Functions",
    subject: ["Algebra 2", "Precalculus", "SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["inverse functions", "logarithm properties", "graphing", "growth and decay"],
    calculatorAllowed: true,
    standardCode: "AA.FGR.3",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "alg2-radical-functions",
    name: "Investigating Radical Functions",
    subject: ["Algebra 2"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["rational exponents", "extraneous solutions", "radical graphs"],
    standardCode: "AA.FGR.4",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "alg2-polynomial-functions",
    name: "Modeling Polynomial Functions",
    subject: ["Algebra 2"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["complex numbers", "zeros of polynomials", "factoring", "end behavior"],
    standardCode: "AA.FGR.5",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "alg2-matrices",
    name: "Linear Algebra and Matrices",
    subject: ["Algebra 2"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["matrix operations", "systems of equations", "linear programming"],
    standardCode: "AA.PAR.6",
    standardName: "Patterning & Algebraic Reasoning",
  },
  {
    id: "alg2-unit-circle",
    name: "Trigonometry and the Unit Circle",
    subject: ["Algebra 2"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["radians", "unit circle", "terminal angles", "trigonometric equations"],
    standardCode: "AA.GSR.7",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "alg2-rational-functions",
    name: "Exploring Rational Functions",
    subject: ["Algebra 2"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["rational expressions", "asymptotes", "real-life modeling"],
    standardCode: "AA.FGR.8",
    standardName: "Functional & Graphical Reasoning",
  },

  // ── Precalculus (Precalculus & AP Precalculus) ──────────────────────────────
  {
    id: "pre-rational-piecewise",
    name: "Rational and Piecewise-Defined Functions",
    subject: ["Precalculus"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["limit notation", "asymptotes", "continuity", "piecewise functions"],
    standardCode: "PC.FGR.2",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "pre-trig-functions",
    name: "Trigonometric Expressions and Functions",
    subject: ["Precalculus"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["unit circle", "six trig ratios", "periodic functions", "inverse trig functions"],
    standardCode: "PC.FGR.3",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "pre-trig-identities",
    name: "Trigonometric Identities and Equations",
    subject: ["Precalculus"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["sum and difference formulas", "double angle", "law of sines", "law of cosines"],
    standardCode: "PC.AGR.4",
    standardName: "Algebraic & Geometric Reasoning",
  },
  {
    id: "pre-conic-polar",
    name: "Conic Sections and Polar Equations",
    subject: ["Precalculus"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["circles", "parabolas", "ellipses", "hyperbolas", "polar coordinates"],
    standardCode: "PC.GSR.5",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "pre-vectors",
    name: "Vector Quantities",
    subject: ["Precalculus"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["vector operations", "parametric equations", "force and velocity"],
    standardCode: "PC.AGR.6",
    standardName: "Algebraic & Graphical Reasoning",
  },
  {
    id: "pre-sequences-series",
    name: "Sequences and Series",
    subject: ["Precalculus", "Algebra 2"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["convergence", "divergence", "geometric series", "sigma notation"],
    standardCode: "PC.PAR.7",
    standardName: "Patterning & Algebraic Reasoning",
  },

  // ── Calculus ─────────────────────────────────────────────────────────────────
  {
    id: "calc-limits-continuity",
    name: "Limits and Continuity",
    subject: ["Calculus"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["limit notation", "asymptotic behavior", "intermediate value theorem"],
    standardCode: "C.FGR.2",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "calc-differentiation",
    name: "Differentiation",
    subject: ["Calculus"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["definition of the derivative", "product rule", "quotient rule", "chain rule"],
    standardCode: "C.FGR.3",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "calc-applications-derivatives",
    name: "Applications of Derivatives",
    subject: ["Calculus"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["curve analysis", "optimization", "related rates", "mean value theorem"],
    standardCode: "C.FGR.4",
    standardName: "Functional & Graphical Reasoning",
  },
  {
    id: "calc-integrals",
    name: "Definite and Indefinite Integrals",
    subject: ["Calculus"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["Riemann sums", "Fundamental Theorem of Calculus", "antiderivatives"],
    standardCode: "C.GSR.5",
    standardName: "Geometric & Spatial Reasoning",
  },
  {
    id: "calc-integral-applications",
    name: "Applications of Integrals",
    subject: ["Calculus"],
    domain: "Math",
    difficulty: "advanced",
    tags: ["separable differential equations", "area between curves", "average value"],
    standardCode: "C.PAR.6",
    standardName: "Patterning & Algebraic Reasoning",
  },

  // ── SAT/ACT Math (test-specific, not a standalone GA course) ───────────────
  {
    id: "sat-percents",
    name: "Percents",
    subject: ["SAT/ACT Math"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["percent change", "markup", "discount", "word problems"],
    calculatorAllowed: true,
  },
  {
    id: "sat-ratios",
    name: "Ratios and Proportions",
    subject: ["SAT/ACT Math"],
    domain: "Math",
    difficulty: "foundational",
    tags: ["unit rates", "proportional reasoning", "unit conversion"],
    calculatorAllowed: true,
  },
  {
    id: "sat-function-notation",
    name: "Function Notation",
    subject: ["SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["f(x)", "composition", "evaluation", "inverse"],
    calculatorAllowed: true,
  },
  {
    id: "sat-statistics",
    name: "Statistics and Data Analysis",
    subject: ["SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["mean", "median", "mode", "standard deviation", "scatterplots", "correlation"],
    calculatorAllowed: true,
  },
  {
    id: "sat-problem-context",
    name: "Problem Solving in Context",
    subject: ["SAT/ACT Math"],
    domain: "Math",
    difficulty: "intermediate",
    tags: ["word problems", "modeling", "units", "interpreting expressions"],
    calculatorAllowed: true,
  },

  // ── ELA (Georgia K-12 ELA Standards, 9-12: Language & Texts domains) ────────
  {
    id: "ela-grammar-usage-mechanics",
    name: "Grammar, Usage, and Mechanics",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "foundational",
    tags: ["standard English conventions", "punctuation", "capitalization", "sentence construction"],
    standardCode: "9-12.L.GC.1",
    standardName: "Grammar Conventions",
  },
  {
    id: "ela-syntax",
    name: "Syntax",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["parallel structure", "sentence variety", "active and passive voice"],
    standardCode: "9-12.L.GC.2",
    standardName: "Grammar Conventions",
  },
  {
    id: "ela-vocabulary",
    name: "General, Academic, and Specialized Vocabulary",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "foundational",
    tags: ["academic vocabulary", "disciplinary vocabulary", "context clues"],
    standardCode: "9-12.L.V.1",
    standardName: "Vocabulary",
  },
  {
    id: "ela-word-analysis",
    name: "Word Analysis and Morphology",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "foundational",
    tags: ["Greek and Latin roots", "affixes", "etymology", "parts of speech"],
    standardCode: "9-12.L.V.2",
    standardName: "Vocabulary",
  },
  {
    id: "ela-connotation-denotation",
    name: "Connotation and Nuanced Meaning",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["connotation", "denotation", "word choice", "shades of meaning"],
    standardCode: "9-12.L.V.3",
    standardName: "Vocabulary",
  },
  {
    id: "ela-purpose-audience",
    name: "Purpose and Audience",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "foundational",
    tags: ["author's purpose", "target audience", "voice and tone"],
    standardCode: "9-12.T.C.1",
    standardName: "Context",
  },
  {
    id: "ela-authors-perspective",
    name: "Authors' and Speakers' Perspectives",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["bias", "credibility", "historical context", "commercial influence"],
    standardCode: "9-12.T.C.2",
    standardName: "Context",
  },
  {
    id: "ela-organization",
    name: "Organizational Structure",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "foundational",
    tags: ["text structure", "transitions", "introductions and conclusions"],
    standardCode: "9-12.T.SS.1",
    standardName: "Structure & Style",
  },
  {
    id: "ela-craft-style",
    name: "Author's Craft and Language Style",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["figurative language", "rhetorical language", "tone", "formal style"],
    standardCode: "9-12.T.SS.2",
    standardName: "Structure & Style",
  },
  {
    id: "ela-narrative-techniques",
    name: "Narrative Techniques",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["plot structure", "characterization", "symbolism", "theme"],
    standardCode: "9-12.T.T.1",
    standardName: "Techniques",
  },
  {
    id: "ela-expository-techniques",
    name: "Expository Techniques",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["organizational patterns", "clarity", "conflicting information"],
    standardCode: "9-12.T.T.2",
    standardName: "Techniques",
  },
  {
    id: "ela-argumentative-techniques",
    name: "Argumentative Techniques and Rhetorical Appeals",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "advanced",
    tags: ["ethos", "logos", "pathos", "logical fallacies", "rhetorical devices"],
    standardCode: "9-12.T.T.3",
    standardName: "Techniques",
  },
  {
    id: "ela-poetic-techniques",
    name: "Poetic Techniques",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "advanced",
    tags: ["poetic devices", "form", "meaning and theme"],
    standardCode: "9-12.T.T.4",
    standardName: "Techniques",
  },
  {
    id: "ela-research-inquiry",
    name: "Research and Inquiry",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["research questions", "credible sources", "synthesizing evidence"],
    standardCode: "9-12.T.RA.1",
    standardName: "Research & Analysis",
  },
  {
    id: "ela-citing-sources",
    name: "Curating Sources and Citing Evidence",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "intermediate",
    tags: ["MLA format", "APA format", "works cited", "source validity"],
    standardCode: "9-12.T.RA.2",
    standardName: "Research & Analysis",
  },
  {
    id: "ela-periods-movements",
    name: "Literary Periods and Movements",
    subject: ["ELA"],
    domain: "ELA",
    difficulty: "advanced",
    tags: ["literary history", "archetypes", "genre", "major authors"],
    standardCode: "9-12.T.PM.1",
    standardName: "Periods & Movements",
  },
];

export function getSkillById(id: string): Skill | undefined {
  return SKILLS.find((s) => s.id === id);
}

export function getSkillsBySubject(subject: Subject): Skill[] {
  return SKILLS.filter((s) => s.subject.includes(subject));
}

export function getSkillsByDomain(domain: Skill["domain"]): Skill[] {
  return SKILLS.filter((s) => s.domain === domain);
}
